---
default:
  image: python:3

stages:
  - build
  - test
  - release

molecule:
  stage: test
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection install -r collections/requirements.yml
    - molecule test
  except:
    - tags

build:
  stage: build
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
  except:
    - tags

publish:
  stage: release
  needs: []
  script:
    - sed -i s/{version}/$CI_COMMIT_TAG/ galaxy.yml
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
    - ansible-galaxy collection publish --token $GALAXY_TOKEN jugasit-gcp-${CI_COMMIT_TAG}.tar.gz
  only:
    - tags
...
