---
default:
  image: python:3

stages:
  - build
  - test
  - docs
  - release

molecule roles:
  stage: test
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection install -r collections/requirements.yml
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - chmod 0600 ~/.ssh/id_rsa*
    - molecule test -s default
  except:
    - tags

molecule playbook:
  stage: test
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection install -r collections/requirements.yml
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - chmod 0600 ~/.ssh/id_rsa*
    - molecule test -s playbook
  except:
    - tags

build:
  stage: build
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
  except:
    - tags

pages:
  stage: docs
  needs: []
  script:
    - pip3 install -r docs/requirements.txt
    - make docs
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
  only:
    - tags

publish:
  stage: release
  needs: []
  script:
    - 'sed -i "s/version: 0.0.0/version: ${CI_COMMIT_TAG}/" galaxy.yml'
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
    - ansible-galaxy collection publish --token ${GALAXY_TOKEN} jugasit-gcp-${CI_COMMIT_TAG}.tar.gz
  only:
    - tags
...
