---
default:
  image: python:3

molecule:
  stage: test
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection install -r collections/requirements.yml
    - molecule test

build:
  stage: build
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
...
