---
default:
  image: python:3

lint addresses:
  stage: test
  script:
    - pip3 install -r requirements.txt
    - molecule lint

build:
  stage: build
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
...
