---
default:
  image: python:3

lint:
  stage: test
  needs: []
  script:
    - pip3 install -r requirements.txt
    - molecule lint

build:
  stage: build
  needs: []
  script:
    - pip3 install -r requirements.txt
    - ansible-galaxy collection build
...
