---
- name: Get network info
  google.cloud.gcp_compute_network_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    filters:
      - "name:mlcl-{{ mlcl_prefix }}-*"
  register: found_networks

- name: Verify number of networks
  vars:
    expected: "{{ gcp_networks | length }}"
    actual: "{{ found_networks | community.general.json_query('resources[*].name') | length }}"
  ansible.builtin.assert:
    quiet: true
    that: actual == expected
    fail_msg: >-
      The wrong number of networks were detected,
      expected {{ expected }} but found {{ actual }}

- name: Verify each network
  ansible.builtin.assert:
    quiet: true
    that:
      - actual.name == expected.name
      - actual.description == expected.description
      - actual.mtu == expected.mtu
      - actual.routingConfig.routingMode == expected.routing_config.routing_mode | default('REGIONAL')
  loop: "{{ gcp_networks }}"
  loop_control:
    loop_var: expected
    label: "{{ expected.name }}"
  vars:
    json_query: resources[?name=='{{ expected.name }}']
    actual: "{{ found_networks | community.general.json_query(json_query) | first }}"
...
