---
prerun: false

dependency:
  name: galaxy

driver:
  name: delegated
  gcp_project: ${GCP_PROJECT}
  gcp_service_account_file: ${GCP_CREDENTIALS}
  gcp_region: europe-north1
  gcp_zone: europe-north1-a

platforms:
  - name: instance1
    machine_type: n2-standard-2
    disk: 50
    image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts

  - name: instance2
    machine_type: n2-standard-2
    disk: 50
    image: projects/rhel-cloud/global/images/family/rhel-9

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
...
