---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  vars_files:
    - vars.yml

  vars:
    gcp_state: absent

  roles:
    - addresses
...
