---
- name: Destroy resources in GCP
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  vars_files:
    - vars/common.yml
    - vars/addresses.yml
    - vars/networks.yml
    - vars/firewalls.yml

  vars:
    gcp_state: absent

  roles:
    - addresses
    - firewalls
    - networks
...
