---
- name: Verify resources in GCP
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/common.yml
    - vars/addresses.yml
    - vars/networks.yml
    - vars/firewalls.yml
    - vars/instances.yml

  tasks:
    - include_tasks: tasks/verify_addresses.yml
    - include_tasks: tasks/verify_networks.yml
    - include_tasks: tasks/verify_firewalls.yml
    - include_tasks: tasks/verify_instances.yml
...
